id: '1771400000000'
alias: Living Room Sunshade - French window control
description: >-
  Raises the sunshade when the french window opens (if currently closed).
  Closes it back when the window shuts during nighttime.
triggers:
  - alias: French window opened
    trigger: state
    entity_id: binary_sensor.living_room_french_window
    not_from:
      - unavailable
      - unknown
    to: 'on'
    id: opening
  - alias: French window closed
    trigger: state
    entity_id: binary_sensor.living_room_french_window
    not_from:
      - unavailable
      - unknown
    to: 'off'
    id: closing
actions:
  - choose:
      - alias: "Window opened: raise sunshade if it was down"
        conditions:
          - condition: trigger
            id: opening
          - condition: numeric_state
            entity_id: cover.living_room_sunshade
            attribute: current_position
            below: 10
        sequence:
          - alias: Raise sunshade to 70%
            action: cover.set_cover_position
            target:
              entity_id: cover.living_room_sunshade
            data:
              position: 70
      - alias: "Window closed at night: lower sunshade"
        conditions:
          - condition: trigger
            id: closing
          - condition: sun
            after: sunset
            after_offset: "+00:30:00"
            before: sunrise
        sequence:
          - alias: Close sunshade fully
            action: cover.set_cover_position
            target:
              entity_id: cover.living_room_sunshade
            data:
              position: 0
mode: restart
