id: '1771400000000'
alias: Living Room Sunshade - Window control
description: Manages sunshade position based on french window open/close state.
triggers:
  - trigger: state
    entity_id: binary_sensor.living_room_french_window
    to: 'on'
    id: opening
  - trigger: state
    entity_id: binary_sensor.living_room_french_window
    to: 'off'
    id: closing
actions:
  - choose:
      - conditions:
          - condition: trigger
            id: opening
        sequence:
          - alias: Check if sunshade is closed before raising
            if:
              - condition: numeric_state
                entity_id: cover.living_room_sunshade
                attribute: current_position
                below: 6
            then:
              - action: cover.set_cover_position
                target:
                  entity_id: cover.living_room_sunshade
                data:
                  position: 70
      - conditions:
          - condition: trigger
            id: closing
        sequence:
          - action: cover.set_cover_position
            target:
              entity_id: cover.living_room_sunshade
            data:
              position: 0
mode: restart
