id: '1771521471495'
alias: Heat Sync - Living room & General thermostat
description: Keeps the living room valve and general thermostat temperatures aligned.
triggers:
  - alias: General thermostat setpoint changed
    trigger: state
    entity_id: climate.general_thermostat
    attribute: temperature
    not_from:
      - unavailable
      - unknown
  - alias: Living room valve setpoint changed
    trigger: state
    entity_id: climate.living_room_thermostatic_valve_thermostat
    attribute: temperature
    not_from:
      - unavailable
      - unknown
variables:
  living_room_setpoint: "{{ state_attr('climate.living_room_thermostatic_valve_thermostat', 'temperature') | float(0) }}"
  general_setpoint: "{{ state_attr('climate.general_thermostat', 'temperature') | float(0) }}"
actions:
  - choose:
      - alias: Living room valve changed - update general thermostat
        conditions:
          - condition: template
            value_template: >-
              {{ trigger.entity_id == 'climate.living_room_thermostatic_valve_thermostat'
                 and living_room_setpoint != general_setpoint }}
        sequence:
          - action: climate.set_temperature
            target:
              entity_id: climate.general_thermostat
            data:
              temperature: "{{ living_room_setpoint }}"
      - alias: General thermostat changed - update living room valve
        conditions:
          - condition: template
            value_template: >-
              {{ trigger.entity_id == 'climate.general_thermostat'
                 and general_setpoint != living_room_setpoint }}
        sequence:
          - action: climate.set_temperature
            target:
              entity_id: climate.living_room_thermostatic_valve_thermostat
            data:
              temperature: "{{ general_setpoint }}"
mode: restart
