id: '1771521471495'
alias: Heat Sync - General thermostat ↔ Living room with circuit protection
description: >-
  Default: bidirectional sync between general thermostat and living room valve.
  Override: when the living room is about to reach its target but other rooms
  still need heating, bumps the general thermostat to the max active target
  to prevent premature circuit cutoff. Returns to salon sync once all rooms
  are satisfied.
triggers:
  - alias: Living room setpoint changed
    trigger: state
    entity_id: climate.living_room_thermostatic_valve_thermostat
    attribute: temperature
    not_from:
      - unavailable
      - unknown
    id: living_room_setpoint
  - alias: General thermostat setpoint changed
    trigger: state
    entity_id: climate.general_thermostat
    attribute: temperature
    not_from:
      - unavailable
      - unknown
    id: general_setpoint
  - alias: Any room temperature changed
    trigger: state
    entity_id: !include ../../mappings/heaters/thermostats.yaml
    attribute: current_temperature
    not_from:
      - unavailable
      - unknown
    id: temp_update
conditions:
  - alias: Collective heating must be on
    condition: state
    entity_id: input_boolean.collective_heating
    state: "on"
variables:
  salon_target: "{{ state_attr('climate.living_room_thermostatic_valve_thermostat', 'temperature') | float(0) }}"
  general_setpoint: "{{ state_attr('climate.general_thermostat', 'temperature') | float(0) }}"
  desired_general: >
    {% set salon_t = state_attr('climate.living_room_thermostatic_valve_thermostat', 'temperature') | float(0) %}
    {% set salon_c = state_attr('climate.living_room_thermostatic_valve_thermostat', 'current_temperature') | float(0) %}
    {% set non_salon = [
      'climate.bathroom_thermostatic_valve_thermostat',
      'climate.bedroom_thermostatic_valve_thermostat',
      'climate.office_thermostatic_valve_thermostat'
    ] %}
    {% set ns = namespace(max_active=0, has_active=false) %}
    {% for thermo in non_salon %}
      {% set target = state_attr(thermo, 'temperature') | float(0) %}
      {% set current = state_attr(thermo, 'current_temperature') | float(99) %}
      {% if current < target %}
        {% set ns.has_active = true %}
        {% if target > ns.max_active %}
          {% set ns.max_active = target %}
        {% endif %}
      {% endif %}
    {% endfor %}
    {% if (salon_c + 0.5) >= salon_t and ns.has_active %}
      {{ [salon_t, ns.max_active] | max }}
    {% else %}
      {{ salon_t }}
    {% endif %}
actions:
  - alias: "User changed general → sync to living room"
    if:
      - condition: trigger
        id: general_setpoint
      - condition: template
        value_template: "{{ trigger.to_state.attributes.temperature | float != desired_general | float }}"
    then:
      - action: climate.set_temperature
        target:
          entity_id: climate.living_room_thermostatic_valve_thermostat
        data:
          temperature: "{{ trigger.to_state.attributes.temperature | float }}"
  - alias: "Apply desired general setpoint if different and sane"
    if:
      - condition: template
        value_template: >
          {{ desired_general | float != general_setpoint | float
             and desired_general | float >= 5 }}
    then:
      - action: climate.set_temperature
        target:
          entity_id: climate.general_thermostat
        data:
          temperature: "{{ desired_general }}"
mode: restart
