id: '1771400000002'
alias: Light - Balcony outside lamp (french window)
description: >-
  Turns on balcony light when french window opens (or is already open) 
  when the sun is down in winter. Turns off when french window closes.
triggers:
  - alias: French window opened
    trigger: state
    entity_id: binary_sensor.living_room_french_window
    not_from:
      - unavailable
      - unknown
    to: "on"
    id: opening
  - alias: Sun goes below horizon
    trigger: state
    entity_id: sun.sun
    from: "above_horizon"
    to: "below_horizon"
    id: sunset
  - alias: French window closed
    trigger: state
    entity_id: binary_sensor.living_room_french_window
    not_from:
      - unavailable
      - unknown
    to: "off"
    id: closing
actions:
  - alias: Turn off or on based on trigger
    if:
      - condition: trigger
        id: closing
    then:
      - alias: Turn off balcony lamp
        action: switch.turn_off
        target:
          entity_id: switch.balcony_outside_lamp
    else:
      - alias: French window is open
        condition: state
        entity_id: binary_sensor.living_room_french_window
        state: "on"
      - alias: Sun is below horizon
        condition: state
        entity_id: sun.sun
        state: "below_horizon"
      - alias: Winter months only (Nov-Mar)
        condition: template
        value_template: "{{ now().month in [11, 12, 1, 2, 3] }}"
      - alias: Turn on balcony lamp
        action: switch.turn_on
        target:
          entity_id: switch.balcony_outside_lamp
mode: single