id: '1768830672935'
alias: Light sync - Bedroom - OFF
description: ''
triggers:
  - trigger: state
    entity_id: switch.bedroom_ceiling_lamp_switch
    from: 'on'
    to: 'off'
  - trigger: state
    entity_id: light.bedroom_bed_led_strip
    from: 'on'
    to: 'off'
conditions:
  - condition: or
    conditions:
    - condition: state
      entity_id: switch.bedroom_ceiling_lamp_switch
      state: 'on'
    - condition: state
      entity_id: light.bedroom_bed_led_strip
      state: 'on'
actions:
  - action: switch.turn_off
    target:
      entity_id: switch.bedroom_ceiling_lamp_switch
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - action: light.turn_off
    target:
      entity_id: light.bedroom_bed_led_strip
mode: single
