id: '1768830600294'
alias: Light sync - Bedroom - ON
description: ''
triggers:
  - trigger: state
    entity_id: switch.bedroom_ceiling_lamp_switch
    from: 'off'
    to: 'on'
conditions: []
actions:
  - action: light.turn_on
    target:
      entity_id: light.bedroom_bed_led_strip
mode: single
