id: '1768830600295'
alias: Light sync - Bedroom - Bidirectional
description: Bidirectional sync switch ↔ ceiling bulb ↔ LED strip, 1 min delay for LED strip on switch-off (cancelled if switch turns back on)
triggers:
  - trigger: state
    entity_id:
      - switch.bedroom_ceiling_lamp_switch
      - light.bedroom_bed_led_strip
      - light.bedroom_ceiling_lamp_bulb
conditions: []
actions:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state == 'on' }}"
        sequence:
          - if:
              - condition: template
                value_template: "{{ trigger.entity_id == 'switch.bedroom_ceiling_lamp_switch' }}"
            then:
              - action: light.turn_on
                target:
                  entity_id:
                    - light.bedroom_bed_led_strip
                    - light.bedroom_ceiling_lamp_bulb
            else:
              - if:
                  - condition: template
                    value_template: "{{ trigger.entity_id == 'light.bedroom_bed_led_strip' }}"
                then:
                  - action: switch.turn_on
                    target:
                      entity_id: switch.bedroom_ceiling_lamp_switch
                  - action: light.turn_on
                    target:
                      entity_id: light.bedroom_ceiling_lamp_bulb
                else:
                  - action: switch.turn_on
                    target:
                      entity_id: switch.bedroom_ceiling_lamp_switch
                  - action: light.turn_on
                    target:
                      entity_id: light.bedroom_bed_led_strip
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state == 'off' }}"
        sequence:
          - if:
              - condition: template
                value_template: "{{ trigger.entity_id == 'switch.bedroom_ceiling_lamp_switch' }}"
            then:
              - action: light.turn_off
                target:
                  entity_id: light.bedroom_ceiling_lamp_bulb
              - wait_template: "{{ is_state('switch.bedroom_ceiling_lamp_switch', 'on') }}"
                timeout: "00:01:00"
                continue_on_timeout: true
              - choose:
                  - conditions:
                      - condition: template
                        value_template: "{{ is_state('switch.bedroom_ceiling_lamp_switch', 'off') }}"
                    sequence:
                      - action: light.turn_off
                        target:
                          entity_id: light.bedroom_bed_led_strip
                  - conditions: []
                    sequence:
                      - action: light.turn_on
                        target:
                          entity_id:
                            - light.bedroom_ceiling_lamp_bulb
                            - light.bedroom_bed_led_strip
            else:
              - if:
                  - condition: template
                    value_template: "{{ trigger.entity_id == 'light.bedroom_bed_led_strip' }}"
                then:
                  - action: switch.turn_off
                    target:
                      entity_id: switch.bedroom_ceiling_lamp_switch
                  - action: light.turn_off
                    target:
                      entity_id: light.bedroom_ceiling_lamp_bulb
                else:
                  - action: switch.turn_off
                    target:
                      entity_id: switch.bedroom_ceiling_lamp_switch
                  - action: light.turn_off
                    target:
                      entity_id: light.bedroom_bed_led_strip
mode: single
