id: '1768830600295'
alias: Light sync - Bedroom - Switch toggle
description: Switch toggles bulb + LED strip. Bulb off immediately, LED strip after 1 min (cancelled if switch pressed again).
triggers:
  - trigger: state
    entity_id: switch.bedroom_ceiling_lamp_switch
conditions: []
actions:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ is_state('light.bedroom_ceiling_lamp_bulb', 'on') or is_state('light.bedroom_bed_led_strip', 'on') }}"
        sequence:
          - action: light.turn_off
            target:
              entity_id: light.bedroom_ceiling_lamp_bulb
          - wait_template: "{{ is_state('switch.bedroom_ceiling_lamp_switch', 'on') }}"
            timeout: "00:01:00"
            continue_on_timeout: true
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ is_state('switch.bedroom_ceiling_lamp_switch', 'off') }}"
                sequence:
                  - action: light.turn_off
                    target:
                      entity_id: light.bedroom_bed_led_strip
              - conditions: []
                sequence:
                  - action: light.turn_on
                    target:
                      entity_id:
                        - light.bedroom_ceiling_lamp_bulb
                        - light.bedroom_bed_led_strip
      - conditions: []
        sequence:
          - action: light.turn_on
            target:
              entity_id:
                - light.bedroom_ceiling_lamp_bulb
                - light.bedroom_bed_led_strip
mode: single
