id: '1771400000003'
alias: Light Sync - Bedroom switch toggle
description: >-
  Turns off the bulb immediately, waits 60s for the LED strip.
  If the bulb is turned back on during that time, the LED strip stays on.
triggers:
  - alias: Bedroom ceiling lamp switch toggled
    trigger: state
    entity_id: switch.bedroom_ceiling_lamp_switch
    not_from:
      - unavailable
      - unknown
actions:
  - choose:
      - alias: "Bulb is ON: turn off, then conditionally turn off LED strip"
        conditions:
          - condition: state
            entity_id: light.bedroom_ceiling_lamp_bulb
            state: "on"
        sequence:
          - action: light.turn_off
            target:
              entity_id: light.bedroom_ceiling_lamp_bulb
          - alias: Wait up to 60s or until bulb turns back on
            wait_for_trigger:
              - trigger: state
                entity_id: light.bedroom_ceiling_lamp_bulb
                to: "on"
            timeout: "00:01:00"
            continue_on_timeout: true
          - alias: Turn off LED strip only if bulb is still off
            if:
              - condition: state
                entity_id: light.bedroom_ceiling_lamp_bulb
                state: "off"
            then:
              - action: light.turn_off
                target:
                  entity_id: light.bedroom_bed_led_strip
      - alias: "Bulb is OFF: turn on bulb and LED strip"
        conditions:
          - condition: state
            entity_id: light.bedroom_ceiling_lamp_bulb
            state: "off"
        sequence:
          - action: light.turn_on
            target:
              entity_id:
                - light.bedroom_ceiling_lamp_bulb
                - light.bedroom_bed_led_strip
mode: restart
