id: '1765721688168'
alias: Shutters and Sunshade - Close - Global
description: >-
  Close all shutters at sunset. Excludes covers whose window sensor is open
  (mapping in mappings/shutters/cover_window_sensors.yaml).
triggers:
  - alias: 30 min after sunset
    trigger: sun
    event: sunset
    offset: "00:30:00"
variables:
  cover_window_sensors: !include ../../mappings/shutters/cover_window_sensors.yaml
actions:
  - action: cover.stop_cover
    target:
      area_id:
        - office
        - living_room
        - kitchen
        - bedroom
  - delay: { seconds: 1 }
  - variables:
      covers_to_close: >-
        {% set ns = namespace(entities=[]) %}
        {% for cover, sensor in cover_window_sensors.items() %}
          {% if not sensor or not is_state(sensor, 'on') %}
            {% set ns.entities = ns.entities + [cover] %}
          {% endif %}
        {% endfor %}
        {{ ns.entities }}
  - action: cover.set_cover_position
    data:
      position: 0
    target:
      entity_id: "{{ covers_to_close }}"
mode: single
