id: '1765721688168'
alias: Shutters and Sunshade - Close - Global
description: >-
  Close all shutters at sunset. Excludes covers whose window sensor is open (mapping in mappings/shutters/cover_window_sensors.yaml).
triggers:
  - trigger: sun
    event: sunset
    offset: 00:30:00
conditions: []
actions:
  - action: cover.stop_cover
    metadata: {}
    data: {}
    target:
      area_id:
        - office
        - living_room
        - kitchen
        - bedroom
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - variables:
      covers_to_close: >-
        {% set ns = namespace(entities=[]) %}
        {% for cover, sensor in cover_window_sensors.items() %}
          {% if not sensor or not is_state(sensor, 'on') %}
            {% set ns.entities = ns.entities + [cover] %}
          {% endif %}
        {% endfor %}
        {{ ns.entities }}
  - action: cover.set_cover_position
    metadata: {}
    data:
      position: 0
    target:
      entity_id: "{{ covers_to_close }}"
mode: single
variables:
  cover_window_sensors: !include ../../mappings/shutters/cover_window_sensors.yaml
