id: '1765723709414'
alias: Wake Up - Sunrise - Office / Living room / Kitchen
description: Opens office, living room and kitchen shutters 30 min after sunrise.
triggers:
  - alias: 30 min after sunrise
    trigger: sun
    event: sunrise
    offset: "+00:30:00"
actions:
  - alias: Stop any ongoing cover movement
    action: cover.stop_cover
    target:
      area_id:
        - office
        - living_room
        - kitchen
  - delay: { seconds: 1 }
  - alias: Open shutters fully
    action: cover.set_cover_position
    data:
      position: 100
    target:
      area_id:
        - office
        - living_room
        - kitchen
mode: single
