id: '1765745986629'
alias: Wake Up - Phone alarm - Global
description: >-
  Opens all shutters 2 minutes before the phone alarm rings.
  Uses a debounce flag to avoid repeated triggers.
triggers:
  - alias: Phone alarm is within 2 minutes
    trigger: template
    value_template: >-
      {{ states('sensor.pixel_9_pro_next_alarm') not in ['unknown', 'unavailable']
         and now() >= (states('sensor.pixel_9_pro_next_alarm') | as_datetime - timedelta(minutes=2)) }}
conditions:
  - alias: Wake-up not already triggered
    condition: state
    entity_id: input_boolean.wakeup_done
    state: 'off'
actions:
  - alias: Set debounce flag
    action: input_boolean.turn_on
    target:
      entity_id: input_boolean.wakeup_done
  - alias: Open all shutters
    action: cover.set_cover_position
    data:
      position: 100
    target:
      area_id:
        - living_room
        - office
        - kitchen
        - bedroom
  - delay: { minutes: 2 }
  - alias: Reset debounce flag
    action: input_boolean.turn_off
    target:
      entity_id: input_boolean.wakeup_done
mode: single
