id: '1765745986629'
alias: 'Wake UP : Phone - Global'
description: ''
triggers:
  - minutes: /1
    trigger: time_pattern
conditions:
  - condition: template
    value_template: "{{ \n  states('sensor.pixel_9_pro_next_alarm') not in ['unknown','unavailable']
      \n  and \n  now() >= (states('sensor.pixel_9_pro_next_alarm') | as_datetime
      - timedelta(minutes=2))\n}}\n"
    alias: If next phone alarm is in 2 minutes
  - condition: state
    entity_id: input_boolean.wakeup_done
    state: 'off'
actions:
  - action: input_boolean.turn_on
    target:
      entity_id: input_boolean.wakeup_done
  - action: cover.stop_cover
    metadata: {}
    data: {}
    target:
      area_id:
      - office
      - living_room
      - kitchen
      - bedroom
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - action: cover.set_cover_position
    metadata: {}
    data:
      position: 100
    target:
      area_id:
      - living_room
      - office
      - kitchen
      - bedroom
  - delay:
      hours: 0
      minutes: 2
      seconds: 0
      milliseconds: 0
  - action: input_boolean.turn_off
    target:
      entity_id: input_boolean.wakeup_done
mode: single
