id: '1779568000041'
alias: Awtrix - Litter Wastebin Full
description: >-
  Shows a notification on the Awtrix clock when the Petkit Pura MAX wastebin
  is full.
triggers:
  - trigger: state
    entity_id: binary_sensor.auto_litter_wastebin_filled
    to: 'on'
    for: "1m"
actions:
  - action: mqtt.publish
    data:
      topic: awtrix_6f0891c/notify
      payload: >-
        {"text": "Wastebin full", "icon": "18576", "color": "#FF6B00", "duration": 30}
mode: single
