id: '1770911000002'
alias: Bedroom - Remote buttons 1 & 2 - Ceiling light brightness
description: Button 1 = decrease brightness (min 10%), Button 2 = increase brightness. 8 presses = 90% range (10-100%), 1 press = 11.25%.
triggers:
  - trigger: state
    entity_id:
      - event.bedroom_remote_button_1
      - event.bedroom_remote_button_2
conditions: []
actions:
  - alias: Calculate brightness from press count
    variables:
      count: "{{ [8, trigger.to_state.attributes.totalNumberOfPressesCounted | default(1)] | min }}"
      step: "{{ 90 / 8 }}"
      delta: "{{ (step * count) | round(1) }}"
      current_pct: "{{ ((state_attr('light.bedroom_ceiling_lamp_bulb', 'brightness') | default(0)) / 255 * 100) | round(1) }}"
      new_pct: >-
        {% if 'button_1' in trigger.entity_id %}
          {{ [10, current_pct - delta] | max }}
        {% else %}
          {{ [100, current_pct + delta] | min }}
        {% endif %}
  - alias: Set ceiling light brightness
    action: light.turn_on
    target:
      entity_id: light.bedroom_ceiling_lamp_bulb
    data:
      brightness_pct: "{{ new_pct }}"
      transition: 1
mode: single
