id: '1770911000001'
alias: Office - Remote buttons 4 & 5 - Shutter incremental control
description: Button 4 = lower shutter, Button 5 = raise shutter. 8 presses = 100%, 1 press = 12.5%.
triggers:
  - trigger: state
    entity_id:
      - event.office_remote_button_4
      - event.office_remote_button_5
conditions: []
actions:
  - alias: Calculate shutter position from press count
    variables:
      count: "{{ [8, trigger.to_state.attributes.totalNumberOfPressesCounted | default(1)] | min }}"
      step: "{{ 100 / 8 }}"
      delta: "{{ (step * count) | round(1) }}"
      current: "{{ state_attr('cover.office_bso_switch', 'current_position') | default(50) }}"
      new_position: >-
        {% if 'button_4' in trigger.entity_id %}
          {{ [0, current - delta] | max }}
        {% else %}
          {{ [100, current + delta] | min }}
        {% endif %}
  - alias: Set shutter position
    action: cover.set_cover_position
    target:
      entity_id: cover.office_bso_switch
    data:
      position: "{{ new_position }}"
mode: single
