id: '1770910836792'
alias: Remotes - Office - Button 9 - Computer toggle
description: Double press toggles the computer on/off.
triggers:
  - alias: Button 9 pressed
    trigger: state
    entity_id: event.office_remote_button_9
    not_from:
      - unavailable
      - unknown
conditions:
  - alias: Double press only
    condition: template
    value_template: "{{ trigger.to_state.attributes.event_type == 'multi_press_2' }}"
actions:
  - action: script.toggle_on_off_pc_fix
mode: single
